# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/estudiantesdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate — update crea tabla cursos y curso_estudiante automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Deshabilitar caché Thymeleaf en desarrollo
spring.thymeleaf.cache=false
server.port=8080
